/**
 * AVEL's own process scaffold.
 *
 * These four bodies are identical for every mission of every client, so they
 * are versioned with the renderer rather than carried as mission data. That is
 * a decision, not an accident: the alternative is storing four copies of
 * AVEL's boilerplate per mission and letting them drift.
 *
 * The decision-log PREAMBLE is scaffold; its entries are not. An entry names a
 * mission's cut and the evidence for it, so entries are input.
 */
export const SCAFFOLD = {
	dispatchTemplate:
		'# Dispatch: <agent-slug> — <phase>\n\nCopy this file. Do not edit it in place.\n\n## Agent\n\nSlug        <agent-slug>\nPhase       <A | B | C | D>\nKind        <feature | horizontal>\n\n## Objective\n\nOne paragraph. What exists when this dispatch is closed, stated as\nan observable outcome rather than a list of activities.\n\n## Mount\n\nCopied from `roster/roster.json`. That file is authoritative; if this\nsection and the roster disagree, the roster wins and this dispatch is\nwrong.\n\nWritable\n  <glob>\n\nAppend-only\n  <glob>\n\nRead-only\n  <glob>\n\n## Inputs\n\nWhat this agent reads before starting, by path. Contract artifacts,\nconventions, and any upstream edge named in the roster.\n\n## Deliverables\n\nEach one a path or a command that a reader can check without asking\nthe agent. "The service is implemented" is not a deliverable. "GET\n/transactions returns 200 with the contract shape" is.\n\n## Done when\n\nThe commands that must pass, verbatim, and the gates they feed.\n\n## Forbidden\n\nNamed specifically, not by principle. What this agent might\nreasonably reach for that it may not have.\n\n## Blockers\n\nIf anything above forbids something this dispatch requires, file it\nin `process/findings/` with a documented workaround before\nproceeding. Do not absorb it and do not route around the boundary.\n',
	findingsTemplate:
		'# Finding: <short-slug>\n\nCopy this file. Do not edit it in place.\n\n## Class\n\n<blocker | defect | contradiction>\n\nblocker         the dispatch forbids something the work requires\ndefect          the code or the contract is wrong\ncontradiction   two authoritative sources disagree\n\n## Filed by\n\nAgent slug and the dispatch this arose under.\n\n## What was needed\n\nThe specific thing, in one or two sentences. A path, a permission, a\nvalue, a decision.\n\n## Why it is blocked\n\nWhat forbids it, quoted, with the path it came from. Not a summary of\nthe rule, the rule.\n\n## Evidence\n\nWhat was observed, verbatim. Command and output, or file and line. If\na tool errored, say the tool errored; an error is not a result.\n\n## Workaround applied\n\nWhat was done instead, and where it lives. Write this even when the\nworkaround is "nothing, the work stopped here", because a stopped\ndispatch and an absorbed one look identical from outside.\n\n## Cost of the workaround\n\nWhat is now worse than it would have been. If the answer is nothing,\nsay nothing, and expect to be asked again.\n\n## Resolution requested\n\nWhat the operator has to decide or provide. One question, answerable\nyes or no where possible.\n\n## Do not\n\nRoute around the boundary. Absorb this silently. Edit the source of\nthe restriction to unblock yourself.\n',
	reportsTemplate:
		"# Report: <agent-slug> — <phase>\n\nCopy this file. Do not edit it in place.\n\n## Dispatch\n\nThe dispatch this closes, by path.\n\n## Status\n\n<complete | partial | blocked>\n\nPartial and blocked both require the remaining work named below. A\nreport that says complete while work remains is the failure this\nprocess exists to catch.\n\n## What was built\n\nPaths written, grouped by deliverable from the dispatch. Every\ndeliverable in the dispatch appears here, including the ones not\ndone, marked as not done.\n\n## Evidence\n\nCommands run and their result. Paste the summary line, not the whole\nlog.\n\n  <command>\n  <result>\n\nA passing suite means the code ran. It does not mean the tests\nchecked anything. State what the assertions cover.\n\n## Not done\n\nAnything in the dispatch that did not ship, and why. Empty only when\nthe dispatch shipped whole.\n\n## Blockers filed\n\nFindings filed during this dispatch, by path. Empty is a valid answer\nand a suspicious one on a first dispatch.\n\n## Assumptions\n\nDecisions made where the dispatch was silent. Each one is a place the\nnext agent may be surprised.\n\n## For the next agent\n\nWhat the agent picking this up needs and would not find by reading\nthe code.\n",
	decisionLogPreamble:
		"# Decision Log\n\nAppend-only. Every agent on this mission writes here. Nothing in this\nfile is edited or removed once written, including entries that turned\nout to be wrong. A superseded decision is corrected by a later entry\nthat names it, never by a rewrite.\n\nNo timestamps. Ordering is the order of entries, and the sprint and\nphase on each entry place it.\n\n## Entry format\n\nCopy this shape. One decision per entry.\n\n```\n### <sequence> · <agent-slug> · sprint <n> · phase <A|B|C|D>\n\nDecision\n  What was decided, in one sentence, as a statement rather than an\n  intention.\n\nContext\n  What forced the decision. The constraint, the ambiguity, or the\n  finding that made a choice necessary.\n\nAlternatives\n  What else was considered and why it was not taken. An entry with no\n  alternatives is a decision that did not need making.\n\nConsequence\n  What is now true that was not true before, and what it costs.\n\nSupersedes\n  The sequence number of an earlier entry this replaces, or none.\n```",
} as const;
