/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppIntakeRouteImport } from './routes/_app/intake'
import { Route as AppPlaybooksRouteImport } from './routes/_app/playbooks'
import { Route as AppPresetsRouteImport } from './routes/_app/presets'
import { Route as AppCatalogAgentsRouteImport } from './routes/_app/catalog.agents'
import { Route as AppCatalogSkillsRouteImport } from './routes/_app/catalog.skills'
import { Route as AppCatalogSourcesRouteImport } from './routes/_app/catalog.sources'
import { Route as AppMissionsIndexRouteImport } from './routes/_app/missions.index'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings.account'
import { Route as AppSettingsConnectionsRouteImport } from './routes/_app/settings.connections'
import { Route as AppSettingsRepositoriesRouteImport } from './routes/_app/settings.repositories'
import { Route as ApiAuthGithubRouteImport } from './routes/api/auth/github'
import { Route as ApiAuthGithubCallbackRouteImport } from './routes/api/auth/github.callback'
import { Route as AppMissionsMissionIdExportsNewRouteImport } from './routes/_app/missions.$missionId.exports.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppIntakeRoute = AppIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaybooksRoute = AppPlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => AppRoute,
} as any)
const AppPresetsRoute = AppPresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogAgentsRoute = AppCatalogAgentsRouteImport.update({
  id: '/catalog/agents',
  path: '/catalog/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogSkillsRoute = AppCatalogSkillsRouteImport.update({
  id: '/catalog/skills',
  path: '/catalog/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogSourcesRoute = AppCatalogSourcesRouteImport.update({
  id: '/catalog/sources',
  path: '/catalog/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionsIndexRoute = AppMissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsConnectionsRoute = AppSettingsConnectionsRouteImport.update({
  id: '/settings/connections',
  path: '/settings/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRepositoriesRoute = AppSettingsRepositoriesRouteImport.update({
  id: '/settings/repositories',
  path: '/settings/repositories',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthGithubRoute = ApiAuthGithubRouteImport.update({
  id: '/api/auth/github',
  path: '/api/auth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGithubCallbackRoute = ApiAuthGithubCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGithubRoute,
} as any)
const AppMissionsMissionIdExportsNewRoute =
  AppMissionsMissionIdExportsNewRouteImport.update({
    id: '/missions/$missionId/exports/new',
    path: '/missions/$missionId/exports/new',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AppActivityRoute
  '/clients': typeof AppClientsRoute
  '/intake': typeof AppIntakeRoute
  '/playbooks': typeof AppPlaybooksRoute
  '/presets': typeof AppPresetsRoute
  '/catalog/agents': typeof AppCatalogAgentsRoute
  '/catalog/skills': typeof AppCatalogSkillsRoute
  '/catalog/sources': typeof AppCatalogSourcesRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/connections': typeof AppSettingsConnectionsRoute
  '/settings/repositories': typeof AppSettingsRepositoriesRoute
  '/api/auth/github': typeof ApiAuthGithubRouteWithChildren
  '/missions/': typeof AppMissionsIndexRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/missions/$missionId/exports/new': typeof AppMissionsMissionIdExportsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AppActivityRoute
  '/clients': typeof AppClientsRoute
  '/intake': typeof AppIntakeRoute
  '/playbooks': typeof AppPlaybooksRoute
  '/presets': typeof AppPresetsRoute
  '/catalog/agents': typeof AppCatalogAgentsRoute
  '/catalog/skills': typeof AppCatalogSkillsRoute
  '/catalog/sources': typeof AppCatalogSourcesRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/connections': typeof AppSettingsConnectionsRoute
  '/settings/repositories': typeof AppSettingsRepositoriesRoute
  '/api/auth/github': typeof ApiAuthGithubRouteWithChildren
  '/missions': typeof AppMissionsIndexRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/missions/$missionId/exports/new': typeof AppMissionsMissionIdExportsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/intake': typeof AppIntakeRoute
  '/_app/playbooks': typeof AppPlaybooksRoute
  '/_app/presets': typeof AppPresetsRoute
  '/_app/catalog/agents': typeof AppCatalogAgentsRoute
  '/_app/catalog/skills': typeof AppCatalogSkillsRoute
  '/_app/catalog/sources': typeof AppCatalogSourcesRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/connections': typeof AppSettingsConnectionsRoute
  '/_app/settings/repositories': typeof AppSettingsRepositoriesRoute
  '/api/auth/github': typeof ApiAuthGithubRouteWithChildren
  '/_app/missions/': typeof AppMissionsIndexRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/_app/missions/$missionId/exports/new': typeof AppMissionsMissionIdExportsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity'
    | '/clients'
    | '/intake'
    | '/playbooks'
    | '/presets'
    | '/catalog/agents'
    | '/catalog/skills'
    | '/catalog/sources'
    | '/settings/account'
    | '/settings/connections'
    | '/settings/repositories'
    | '/api/auth/github'
    | '/missions/'
    | '/api/auth/github/callback'
    | '/missions/$missionId/exports/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activity'
    | '/clients'
    | '/intake'
    | '/playbooks'
    | '/presets'
    | '/catalog/agents'
    | '/catalog/skills'
    | '/catalog/sources'
    | '/settings/account'
    | '/settings/connections'
    | '/settings/repositories'
    | '/api/auth/github'
    | '/missions'
    | '/api/auth/github/callback'
    | '/missions/$missionId/exports/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/activity'
    | '/_app/clients'
    | '/_app/intake'
    | '/_app/playbooks'
    | '/_app/presets'
    | '/_app/catalog/agents'
    | '/_app/catalog/skills'
    | '/_app/catalog/sources'
    | '/_app/settings/account'
    | '/_app/settings/connections'
    | '/_app/settings/repositories'
    | '/api/auth/github'
    | '/_app/missions/'
    | '/api/auth/github/callback'
    | '/_app/missions/$missionId/exports/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthGithubRoute: typeof ApiAuthGithubRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intake': {
      id: '/_app/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AppIntakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playbooks': {
      id: '/_app/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof AppPlaybooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/presets': {
      id: '/_app/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof AppPresetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/agents': {
      id: '/_app/catalog/agents'
      path: '/catalog/agents'
      fullPath: '/catalog/agents'
      preLoaderRoute: typeof AppCatalogAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/skills': {
      id: '/_app/catalog/skills'
      path: '/catalog/skills'
      fullPath: '/catalog/skills'
      preLoaderRoute: typeof AppCatalogSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/sources': {
      id: '/_app/catalog/sources'
      path: '/catalog/sources'
      fullPath: '/catalog/sources'
      preLoaderRoute: typeof AppCatalogSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/missions/': {
      id: '/_app/missions/'
      path: '/missions'
      fullPath: '/missions/'
      preLoaderRoute: typeof AppMissionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/connections': {
      id: '/_app/settings/connections'
      path: '/settings/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof AppSettingsConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/repositories': {
      id: '/_app/settings/repositories'
      path: '/settings/repositories'
      fullPath: '/settings/repositories'
      preLoaderRoute: typeof AppSettingsRepositoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/github': {
      id: '/api/auth/github'
      path: '/api/auth/github'
      fullPath: '/api/auth/github'
      preLoaderRoute: typeof ApiAuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github/callback': {
      id: '/api/auth/github/callback'
      path: '/callback'
      fullPath: '/api/auth/github/callback'
      preLoaderRoute: typeof ApiAuthGithubCallbackRouteImport
      parentRoute: typeof ApiAuthGithubRoute
    }
    '/_app/missions/$missionId/exports/new': {
      id: '/_app/missions/$missionId/exports/new'
      path: '/missions/$missionId/exports/new'
      fullPath: '/missions/$missionId/exports/new'
      preLoaderRoute: typeof AppMissionsMissionIdExportsNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppClientsRoute: typeof AppClientsRoute
  AppIntakeRoute: typeof AppIntakeRoute
  AppPlaybooksRoute: typeof AppPlaybooksRoute
  AppPresetsRoute: typeof AppPresetsRoute
  AppCatalogAgentsRoute: typeof AppCatalogAgentsRoute
  AppCatalogSkillsRoute: typeof AppCatalogSkillsRoute
  AppCatalogSourcesRoute: typeof AppCatalogSourcesRoute
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsConnectionsRoute: typeof AppSettingsConnectionsRoute
  AppSettingsRepositoriesRoute: typeof AppSettingsRepositoriesRoute
  AppMissionsIndexRoute: typeof AppMissionsIndexRoute
  AppMissionsMissionIdExportsNewRoute: typeof AppMissionsMissionIdExportsNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppClientsRoute: AppClientsRoute,
  AppIntakeRoute: AppIntakeRoute,
  AppPlaybooksRoute: AppPlaybooksRoute,
  AppPresetsRoute: AppPresetsRoute,
  AppCatalogAgentsRoute: AppCatalogAgentsRoute,
  AppCatalogSkillsRoute: AppCatalogSkillsRoute,
  AppCatalogSourcesRoute: AppCatalogSourcesRoute,
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsConnectionsRoute: AppSettingsConnectionsRoute,
  AppSettingsRepositoriesRoute: AppSettingsRepositoriesRoute,
  AppMissionsIndexRoute: AppMissionsIndexRoute,
  AppMissionsMissionIdExportsNewRoute: AppMissionsMissionIdExportsNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiAuthGithubRouteChildren {
  ApiAuthGithubCallbackRoute: typeof ApiAuthGithubCallbackRoute
}

const ApiAuthGithubRouteChildren: ApiAuthGithubRouteChildren = {
  ApiAuthGithubCallbackRoute: ApiAuthGithubCallbackRoute,
}

const ApiAuthGithubRouteWithChildren = ApiAuthGithubRoute._addFileChildren(
  ApiAuthGithubRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthGithubRoute: ApiAuthGithubRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
