/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppPlaybooksRouteImport } from './routes/_app/playbooks'
import { Route as AppPresetsRouteImport } from './routes/_app/presets'
import { Route as ApiClientsRouteImport } from './routes/api/clients'
import { Route as ApiConnectionsRouteImport } from './routes/api/connections'
import { Route as ApiEngagementsRouteImport } from './routes/api/engagements'
import { Route as ApiExportsRouteImport } from './routes/api/exports'
import { Route as ApiIntakesRouteImport } from './routes/api/intakes'
import { Route as ApiMissionsRouteImport } from './routes/api/missions'
import { Route as AppCatalogAgentsRouteImport } from './routes/_app/catalog.agents'
import { Route as AppCatalogSkillsRouteImport } from './routes/_app/catalog.skills'
import { Route as AppCatalogSourcesRouteImport } from './routes/_app/catalog.sources'
import { Route as AppMissionsIndexRouteImport } from './routes/_app/missions.index'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings.account'
import { Route as AppSettingsConnectionsRouteImport } from './routes/_app/settings.connections'
import { Route as AppSettingsRepositoriesRouteImport } from './routes/_app/settings.repositories'
import { Route as ApiAuthGithubRouteImport } from './routes/api/auth/github'
import { Route as ApiClientsIdRouteImport } from './routes/api/clients.$id'
import { Route as ApiConnectionsIdRouteImport } from './routes/api/connections.$id'
import { Route as ApiEngagementsIdRouteImport } from './routes/api/engagements.$id'
import { Route as ApiExportsIdRouteImport } from './routes/api/exports.$id'
import { Route as ApiExportsPreviewRouteImport } from './routes/api/exports.preview'
import { Route as ApiIntakesIdRouteImport } from './routes/api/intakes.$id'
import { Route as ApiMissionsIdRouteImport } from './routes/api/missions.$id'
import { Route as ApiPreflightBlastRadiusRouteImport } from './routes/api/preflight.blast-radius'
import { Route as AppClientsClientIdIndexRouteImport } from './routes/_app/clients.$clientId.index'
import { Route as AppMissionsMissionIdIndexRouteImport } from './routes/_app/missions.$missionId.index'
import { Route as ApiAuthGithubCallbackRouteImport } from './routes/api/auth/github.callback'
import { Route as ApiClientsIdDetailRouteImport } from './routes/api/clients.$id.detail'
import { Route as ApiExportsIdArchiveRouteImport } from './routes/api/exports.$id.archive'
import { Route as ApiIntakesIdPreviewRouteImport } from './routes/api/intakes.$id.preview'
import { Route as ApiMissionsIdRosterRouteImport } from './routes/api/missions.$id.roster'
import { Route as AppClientsClientIdRequestsRequestIdRouteImport } from './routes/_app/clients.$clientId.requests.$requestId'
import { Route as AppMissionsMissionIdExportsNewRouteImport } from './routes/_app/missions.$missionId.exports.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaybooksRoute = AppPlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => AppRoute,
} as any)
const AppPresetsRoute = AppPresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => AppRoute,
} as any)
const ApiClientsRoute = ApiClientsRouteImport.update({
  id: '/api/clients',
  path: '/api/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectionsRoute = ApiConnectionsRouteImport.update({
  id: '/api/connections',
  path: '/api/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEngagementsRoute = ApiEngagementsRouteImport.update({
  id: '/api/engagements',
  path: '/api/engagements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportsRoute = ApiExportsRouteImport.update({
  id: '/api/exports',
  path: '/api/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntakesRoute = ApiIntakesRouteImport.update({
  id: '/api/intakes',
  path: '/api/intakes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMissionsRoute = ApiMissionsRouteImport.update({
  id: '/api/missions',
  path: '/api/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCatalogAgentsRoute = AppCatalogAgentsRouteImport.update({
  id: '/catalog/agents',
  path: '/catalog/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogSkillsRoute = AppCatalogSkillsRouteImport.update({
  id: '/catalog/skills',
  path: '/catalog/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogSourcesRoute = AppCatalogSourcesRouteImport.update({
  id: '/catalog/sources',
  path: '/catalog/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionsIndexRoute = AppMissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsConnectionsRoute = AppSettingsConnectionsRouteImport.update({
  id: '/settings/connections',
  path: '/settings/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRepositoriesRoute = AppSettingsRepositoriesRouteImport.update({
  id: '/settings/repositories',
  path: '/settings/repositories',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthGithubRoute = ApiAuthGithubRouteImport.update({
  id: '/api/auth/github',
  path: '/api/auth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientsIdRoute = ApiClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiClientsRoute,
} as any)
const ApiConnectionsIdRoute = ApiConnectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiConnectionsRoute,
} as any)
const ApiEngagementsIdRoute = ApiEngagementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiEngagementsRoute,
} as any)
const ApiExportsIdRoute = ApiExportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiExportsRoute,
} as any)
const ApiExportsPreviewRoute = ApiExportsPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ApiExportsRoute,
} as any)
const ApiIntakesIdRoute = ApiIntakesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiIntakesRoute,
} as any)
const ApiMissionsIdRoute = ApiMissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMissionsRoute,
} as any)
const ApiPreflightBlastRadiusRoute = ApiPreflightBlastRadiusRouteImport.update({
  id: '/api/preflight/blast-radius',
  path: '/api/preflight/blast-radius',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientsClientIdIndexRoute = AppClientsClientIdIndexRouteImport.update({
  id: '/$clientId/',
  path: '/$clientId/',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppMissionsMissionIdIndexRoute =
  AppMissionsMissionIdIndexRouteImport.update({
    id: '/missions/$missionId/',
    path: '/missions/$missionId/',
    getParentRoute: () => AppRoute,
  } as any)
const ApiAuthGithubCallbackRoute = ApiAuthGithubCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGithubRoute,
} as any)
const ApiClientsIdDetailRoute = ApiClientsIdDetailRouteImport.update({
  id: '/detail',
  path: '/detail',
  getParentRoute: () => ApiClientsIdRoute,
} as any)
const ApiExportsIdArchiveRoute = ApiExportsIdArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => ApiExportsIdRoute,
} as any)
const ApiIntakesIdPreviewRoute = ApiIntakesIdPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ApiIntakesIdRoute,
} as any)
const ApiMissionsIdRosterRoute = ApiMissionsIdRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => ApiMissionsIdRoute,
} as any)
const AppClientsClientIdRequestsRequestIdRoute =
  AppClientsClientIdRequestsRequestIdRouteImport.update({
    id: '/$clientId/requests/$requestId',
    path: '/$clientId/requests/$requestId',
    getParentRoute: () => AppClientsRoute,
  } as any)
const AppMissionsMissionIdExportsNewRoute =
  AppMissionsMissionIdExportsNewRouteImport.update({
    id: '/missions/$missionId/exports/new',
    path: '/missions/$missionId/exports/new',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AppActivityRoute
  '/clients': typeof AppClientsRouteWithChildren
  '/playbooks': typeof AppPlaybooksRoute
  '/presets': typeof AppPresetsRoute
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/connections': typeof ApiConnectionsRouteWithChildren
  '/api/engagements': typeof ApiEngagementsRouteWithChildren
  '/api/exports': typeof ApiExportsRouteWithChildren
  '/api/intakes': typeof ApiIntakesRouteWithChildren
  '/api/missions': typeof ApiMissionsRouteWithChildren
  '/catalog/agents': typeof AppCatalogAgentsRoute
  '/catalog/skills': typeof AppCatalogSkillsRoute
  '/catalog/sources': typeof AppCatalogSourcesRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/connections': typeof AppSettingsConnectionsRoute
  '/settings/repositories': typeof AppSettingsRepositoriesRoute
  '/api/auth/github': typeof ApiAuthGithubRouteWithChildren
  '/api/clients/$id': typeof ApiClientsIdRouteWithChildren
  '/api/connections/$id': typeof ApiConnectionsIdRoute
  '/api/engagements/$id': typeof ApiEngagementsIdRoute
  '/api/exports/$id': typeof ApiExportsIdRouteWithChildren
  '/api/exports/preview': typeof ApiExportsPreviewRoute
  '/api/intakes/$id': typeof ApiIntakesIdRouteWithChildren
  '/api/missions/$id': typeof ApiMissionsIdRouteWithChildren
  '/api/preflight/blast-radius': typeof ApiPreflightBlastRadiusRoute
  '/missions/': typeof AppMissionsIndexRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/clients/$id/detail': typeof ApiClientsIdDetailRoute
  '/api/exports/$id/archive': typeof ApiExportsIdArchiveRoute
  '/api/intakes/$id/preview': typeof ApiIntakesIdPreviewRoute
  '/api/missions/$id/roster': typeof ApiMissionsIdRosterRoute
  '/clients/$clientId/': typeof AppClientsClientIdIndexRoute
  '/missions/$missionId/': typeof AppMissionsMissionIdIndexRoute
  '/clients/$clientId/requests/$requestId': typeof AppClientsClientIdRequestsRequestIdRoute
  '/missions/$missionId/exports/new': typeof AppMissionsMissionIdExportsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AppActivityRoute
  '/clients': typeof AppClientsRouteWithChildren
  '/playbooks': typeof AppPlaybooksRoute
  '/presets': typeof AppPresetsRoute
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/connections': typeof ApiConnectionsRouteWithChildren
  '/api/engagements': typeof ApiEngagementsRouteWithChildren
  '/api/exports': typeof ApiExportsRouteWithChildren
  '/api/intakes': typeof ApiIntakesRouteWithChildren
  '/api/missions': typeof ApiMissionsRouteWithChildren
  '/catalog/agents': typeof AppCatalogAgentsRoute
  '/catalog/skills': typeof AppCatalogSkillsRoute
  '/catalog/sources': typeof AppCatalogSourcesRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/connections': typeof AppSettingsConnectionsRoute
  '/settings/repositories': typeof AppSettingsRepositoriesRoute
  '/api/auth/github': typeof ApiAuthGithubRouteWithChildren
  '/api/clients/$id': typeof ApiClientsIdRouteWithChildren
  '/api/connections/$id': typeof ApiConnectionsIdRoute
  '/api/engagements/$id': typeof ApiEngagementsIdRoute
  '/api/exports/$id': typeof ApiExportsIdRouteWithChildren
  '/api/exports/preview': typeof ApiExportsPreviewRoute
  '/api/intakes/$id': typeof ApiIntakesIdRouteWithChildren
  '/api/missions/$id': typeof ApiMissionsIdRouteWithChildren
  '/api/preflight/blast-radius': typeof ApiPreflightBlastRadiusRoute
  '/missions': typeof AppMissionsIndexRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/clients/$id/detail': typeof ApiClientsIdDetailRoute
  '/api/exports/$id/archive': typeof ApiExportsIdArchiveRoute
  '/api/intakes/$id/preview': typeof ApiIntakesIdPreviewRoute
  '/api/missions/$id/roster': typeof ApiMissionsIdRosterRoute
  '/clients/$clientId': typeof AppClientsClientIdIndexRoute
  '/missions/$missionId': typeof AppMissionsMissionIdIndexRoute
  '/clients/$clientId/requests/$requestId': typeof AppClientsClientIdRequestsRequestIdRoute
  '/missions/$missionId/exports/new': typeof AppMissionsMissionIdExportsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/clients': typeof AppClientsRouteWithChildren
  '/_app/playbooks': typeof AppPlaybooksRoute
  '/_app/presets': typeof AppPresetsRoute
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/connections': typeof ApiConnectionsRouteWithChildren
  '/api/engagements': typeof ApiEngagementsRouteWithChildren
  '/api/exports': typeof ApiExportsRouteWithChildren
  '/api/intakes': typeof ApiIntakesRouteWithChildren
  '/api/missions': typeof ApiMissionsRouteWithChildren
  '/_app/catalog/agents': typeof AppCatalogAgentsRoute
  '/_app/catalog/skills': typeof AppCatalogSkillsRoute
  '/_app/catalog/sources': typeof AppCatalogSourcesRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/connections': typeof AppSettingsConnectionsRoute
  '/_app/settings/repositories': typeof AppSettingsRepositoriesRoute
  '/api/auth/github': typeof ApiAuthGithubRouteWithChildren
  '/api/clients/$id': typeof ApiClientsIdRouteWithChildren
  '/api/connections/$id': typeof ApiConnectionsIdRoute
  '/api/engagements/$id': typeof ApiEngagementsIdRoute
  '/api/exports/$id': typeof ApiExportsIdRouteWithChildren
  '/api/exports/preview': typeof ApiExportsPreviewRoute
  '/api/intakes/$id': typeof ApiIntakesIdRouteWithChildren
  '/api/missions/$id': typeof ApiMissionsIdRouteWithChildren
  '/api/preflight/blast-radius': typeof ApiPreflightBlastRadiusRoute
  '/_app/missions/': typeof AppMissionsIndexRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/clients/$id/detail': typeof ApiClientsIdDetailRoute
  '/api/exports/$id/archive': typeof ApiExportsIdArchiveRoute
  '/api/intakes/$id/preview': typeof ApiIntakesIdPreviewRoute
  '/api/missions/$id/roster': typeof ApiMissionsIdRosterRoute
  '/_app/clients/$clientId/': typeof AppClientsClientIdIndexRoute
  '/_app/missions/$missionId/': typeof AppMissionsMissionIdIndexRoute
  '/_app/clients/$clientId/requests/$requestId': typeof AppClientsClientIdRequestsRequestIdRoute
  '/_app/missions/$missionId/exports/new': typeof AppMissionsMissionIdExportsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity'
    | '/clients'
    | '/playbooks'
    | '/presets'
    | '/api/clients'
    | '/api/connections'
    | '/api/engagements'
    | '/api/exports'
    | '/api/intakes'
    | '/api/missions'
    | '/catalog/agents'
    | '/catalog/skills'
    | '/catalog/sources'
    | '/settings/account'
    | '/settings/connections'
    | '/settings/repositories'
    | '/api/auth/github'
    | '/api/clients/$id'
    | '/api/connections/$id'
    | '/api/engagements/$id'
    | '/api/exports/$id'
    | '/api/exports/preview'
    | '/api/intakes/$id'
    | '/api/missions/$id'
    | '/api/preflight/blast-radius'
    | '/missions/'
    | '/api/auth/github/callback'
    | '/api/clients/$id/detail'
    | '/api/exports/$id/archive'
    | '/api/intakes/$id/preview'
    | '/api/missions/$id/roster'
    | '/clients/$clientId/'
    | '/missions/$missionId/'
    | '/clients/$clientId/requests/$requestId'
    | '/missions/$missionId/exports/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activity'
    | '/clients'
    | '/playbooks'
    | '/presets'
    | '/api/clients'
    | '/api/connections'
    | '/api/engagements'
    | '/api/exports'
    | '/api/intakes'
    | '/api/missions'
    | '/catalog/agents'
    | '/catalog/skills'
    | '/catalog/sources'
    | '/settings/account'
    | '/settings/connections'
    | '/settings/repositories'
    | '/api/auth/github'
    | '/api/clients/$id'
    | '/api/connections/$id'
    | '/api/engagements/$id'
    | '/api/exports/$id'
    | '/api/exports/preview'
    | '/api/intakes/$id'
    | '/api/missions/$id'
    | '/api/preflight/blast-radius'
    | '/missions'
    | '/api/auth/github/callback'
    | '/api/clients/$id/detail'
    | '/api/exports/$id/archive'
    | '/api/intakes/$id/preview'
    | '/api/missions/$id/roster'
    | '/clients/$clientId'
    | '/missions/$missionId'
    | '/clients/$clientId/requests/$requestId'
    | '/missions/$missionId/exports/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/activity'
    | '/_app/clients'
    | '/_app/playbooks'
    | '/_app/presets'
    | '/api/clients'
    | '/api/connections'
    | '/api/engagements'
    | '/api/exports'
    | '/api/intakes'
    | '/api/missions'
    | '/_app/catalog/agents'
    | '/_app/catalog/skills'
    | '/_app/catalog/sources'
    | '/_app/settings/account'
    | '/_app/settings/connections'
    | '/_app/settings/repositories'
    | '/api/auth/github'
    | '/api/clients/$id'
    | '/api/connections/$id'
    | '/api/engagements/$id'
    | '/api/exports/$id'
    | '/api/exports/preview'
    | '/api/intakes/$id'
    | '/api/missions/$id'
    | '/api/preflight/blast-radius'
    | '/_app/missions/'
    | '/api/auth/github/callback'
    | '/api/clients/$id/detail'
    | '/api/exports/$id/archive'
    | '/api/intakes/$id/preview'
    | '/api/missions/$id/roster'
    | '/_app/clients/$clientId/'
    | '/_app/missions/$missionId/'
    | '/_app/clients/$clientId/requests/$requestId'
    | '/_app/missions/$missionId/exports/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiClientsRoute: typeof ApiClientsRouteWithChildren
  ApiConnectionsRoute: typeof ApiConnectionsRouteWithChildren
  ApiEngagementsRoute: typeof ApiEngagementsRouteWithChildren
  ApiExportsRoute: typeof ApiExportsRouteWithChildren
  ApiIntakesRoute: typeof ApiIntakesRouteWithChildren
  ApiMissionsRoute: typeof ApiMissionsRouteWithChildren
  ApiAuthGithubRoute: typeof ApiAuthGithubRouteWithChildren
  ApiPreflightBlastRadiusRoute: typeof ApiPreflightBlastRadiusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playbooks': {
      id: '/_app/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof AppPlaybooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/presets': {
      id: '/_app/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof AppPresetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/clients': {
      id: '/api/clients'
      path: '/api/clients'
      fullPath: '/api/clients'
      preLoaderRoute: typeof ApiClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connections': {
      id: '/api/connections'
      path: '/api/connections'
      fullPath: '/api/connections'
      preLoaderRoute: typeof ApiConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/engagements': {
      id: '/api/engagements'
      path: '/api/engagements'
      fullPath: '/api/engagements'
      preLoaderRoute: typeof ApiEngagementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exports': {
      id: '/api/exports'
      path: '/api/exports'
      fullPath: '/api/exports'
      preLoaderRoute: typeof ApiExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intakes': {
      id: '/api/intakes'
      path: '/api/intakes'
      fullPath: '/api/intakes'
      preLoaderRoute: typeof ApiIntakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/missions': {
      id: '/api/missions'
      path: '/api/missions'
      fullPath: '/api/missions'
      preLoaderRoute: typeof ApiMissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/catalog/agents': {
      id: '/_app/catalog/agents'
      path: '/catalog/agents'
      fullPath: '/catalog/agents'
      preLoaderRoute: typeof AppCatalogAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/skills': {
      id: '/_app/catalog/skills'
      path: '/catalog/skills'
      fullPath: '/catalog/skills'
      preLoaderRoute: typeof AppCatalogSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/sources': {
      id: '/_app/catalog/sources'
      path: '/catalog/sources'
      fullPath: '/catalog/sources'
      preLoaderRoute: typeof AppCatalogSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/missions/': {
      id: '/_app/missions/'
      path: '/missions'
      fullPath: '/missions/'
      preLoaderRoute: typeof AppMissionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/connections': {
      id: '/_app/settings/connections'
      path: '/settings/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof AppSettingsConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/repositories': {
      id: '/_app/settings/repositories'
      path: '/settings/repositories'
      fullPath: '/settings/repositories'
      preLoaderRoute: typeof AppSettingsRepositoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/github': {
      id: '/api/auth/github'
      path: '/api/auth/github'
      fullPath: '/api/auth/github'
      preLoaderRoute: typeof ApiAuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients/$id': {
      id: '/api/clients/$id'
      path: '/$id'
      fullPath: '/api/clients/$id'
      preLoaderRoute: typeof ApiClientsIdRouteImport
      parentRoute: typeof ApiClientsRoute
    }
    '/api/connections/$id': {
      id: '/api/connections/$id'
      path: '/$id'
      fullPath: '/api/connections/$id'
      preLoaderRoute: typeof ApiConnectionsIdRouteImport
      parentRoute: typeof ApiConnectionsRoute
    }
    '/api/engagements/$id': {
      id: '/api/engagements/$id'
      path: '/$id'
      fullPath: '/api/engagements/$id'
      preLoaderRoute: typeof ApiEngagementsIdRouteImport
      parentRoute: typeof ApiEngagementsRoute
    }
    '/api/exports/$id': {
      id: '/api/exports/$id'
      path: '/$id'
      fullPath: '/api/exports/$id'
      preLoaderRoute: typeof ApiExportsIdRouteImport
      parentRoute: typeof ApiExportsRoute
    }
    '/api/exports/preview': {
      id: '/api/exports/preview'
      path: '/preview'
      fullPath: '/api/exports/preview'
      preLoaderRoute: typeof ApiExportsPreviewRouteImport
      parentRoute: typeof ApiExportsRoute
    }
    '/api/intakes/$id': {
      id: '/api/intakes/$id'
      path: '/$id'
      fullPath: '/api/intakes/$id'
      preLoaderRoute: typeof ApiIntakesIdRouteImport
      parentRoute: typeof ApiIntakesRoute
    }
    '/api/missions/$id': {
      id: '/api/missions/$id'
      path: '/$id'
      fullPath: '/api/missions/$id'
      preLoaderRoute: typeof ApiMissionsIdRouteImport
      parentRoute: typeof ApiMissionsRoute
    }
    '/api/preflight/blast-radius': {
      id: '/api/preflight/blast-radius'
      path: '/api/preflight/blast-radius'
      fullPath: '/api/preflight/blast-radius'
      preLoaderRoute: typeof ApiPreflightBlastRadiusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/clients/$clientId/': {
      id: '/_app/clients/$clientId/'
      path: '/$clientId'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof AppClientsClientIdIndexRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/_app/missions/$missionId/': {
      id: '/_app/missions/$missionId/'
      path: '/missions/$missionId'
      fullPath: '/missions/$missionId/'
      preLoaderRoute: typeof AppMissionsMissionIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/github/callback': {
      id: '/api/auth/github/callback'
      path: '/callback'
      fullPath: '/api/auth/github/callback'
      preLoaderRoute: typeof ApiAuthGithubCallbackRouteImport
      parentRoute: typeof ApiAuthGithubRoute
    }
    '/api/clients/$id/detail': {
      id: '/api/clients/$id/detail'
      path: '/detail'
      fullPath: '/api/clients/$id/detail'
      preLoaderRoute: typeof ApiClientsIdDetailRouteImport
      parentRoute: typeof ApiClientsIdRoute
    }
    '/api/exports/$id/archive': {
      id: '/api/exports/$id/archive'
      path: '/archive'
      fullPath: '/api/exports/$id/archive'
      preLoaderRoute: typeof ApiExportsIdArchiveRouteImport
      parentRoute: typeof ApiExportsIdRoute
    }
    '/api/intakes/$id/preview': {
      id: '/api/intakes/$id/preview'
      path: '/preview'
      fullPath: '/api/intakes/$id/preview'
      preLoaderRoute: typeof ApiIntakesIdPreviewRouteImport
      parentRoute: typeof ApiIntakesIdRoute
    }
    '/api/missions/$id/roster': {
      id: '/api/missions/$id/roster'
      path: '/roster'
      fullPath: '/api/missions/$id/roster'
      preLoaderRoute: typeof ApiMissionsIdRosterRouteImport
      parentRoute: typeof ApiMissionsIdRoute
    }
    '/_app/clients/$clientId/requests/$requestId': {
      id: '/_app/clients/$clientId/requests/$requestId'
      path: '/$clientId/requests/$requestId'
      fullPath: '/clients/$clientId/requests/$requestId'
      preLoaderRoute: typeof AppClientsClientIdRequestsRequestIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/_app/missions/$missionId/exports/new': {
      id: '/_app/missions/$missionId/exports/new'
      path: '/missions/$missionId/exports/new'
      fullPath: '/missions/$missionId/exports/new'
      preLoaderRoute: typeof AppMissionsMissionIdExportsNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppClientsRouteChildren {
  AppClientsClientIdIndexRoute: typeof AppClientsClientIdIndexRoute
  AppClientsClientIdRequestsRequestIdRoute: typeof AppClientsClientIdRequestsRequestIdRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsClientIdIndexRoute: AppClientsClientIdIndexRoute,
  AppClientsClientIdRequestsRequestIdRoute:
    AppClientsClientIdRequestsRequestIdRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppPlaybooksRoute: typeof AppPlaybooksRoute
  AppPresetsRoute: typeof AppPresetsRoute
  AppCatalogAgentsRoute: typeof AppCatalogAgentsRoute
  AppCatalogSkillsRoute: typeof AppCatalogSkillsRoute
  AppCatalogSourcesRoute: typeof AppCatalogSourcesRoute
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsConnectionsRoute: typeof AppSettingsConnectionsRoute
  AppSettingsRepositoriesRoute: typeof AppSettingsRepositoriesRoute
  AppMissionsIndexRoute: typeof AppMissionsIndexRoute
  AppMissionsMissionIdIndexRoute: typeof AppMissionsMissionIdIndexRoute
  AppMissionsMissionIdExportsNewRoute: typeof AppMissionsMissionIdExportsNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppPlaybooksRoute: AppPlaybooksRoute,
  AppPresetsRoute: AppPresetsRoute,
  AppCatalogAgentsRoute: AppCatalogAgentsRoute,
  AppCatalogSkillsRoute: AppCatalogSkillsRoute,
  AppCatalogSourcesRoute: AppCatalogSourcesRoute,
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsConnectionsRoute: AppSettingsConnectionsRoute,
  AppSettingsRepositoriesRoute: AppSettingsRepositoriesRoute,
  AppMissionsIndexRoute: AppMissionsIndexRoute,
  AppMissionsMissionIdIndexRoute: AppMissionsMissionIdIndexRoute,
  AppMissionsMissionIdExportsNewRoute: AppMissionsMissionIdExportsNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiClientsIdRouteChildren {
  ApiClientsIdDetailRoute: typeof ApiClientsIdDetailRoute
}

const ApiClientsIdRouteChildren: ApiClientsIdRouteChildren = {
  ApiClientsIdDetailRoute: ApiClientsIdDetailRoute,
}

const ApiClientsIdRouteWithChildren = ApiClientsIdRoute._addFileChildren(
  ApiClientsIdRouteChildren,
)

interface ApiClientsRouteChildren {
  ApiClientsIdRoute: typeof ApiClientsIdRouteWithChildren
}

const ApiClientsRouteChildren: ApiClientsRouteChildren = {
  ApiClientsIdRoute: ApiClientsIdRouteWithChildren,
}

const ApiClientsRouteWithChildren = ApiClientsRoute._addFileChildren(
  ApiClientsRouteChildren,
)

interface ApiConnectionsRouteChildren {
  ApiConnectionsIdRoute: typeof ApiConnectionsIdRoute
}

const ApiConnectionsRouteChildren: ApiConnectionsRouteChildren = {
  ApiConnectionsIdRoute: ApiConnectionsIdRoute,
}

const ApiConnectionsRouteWithChildren = ApiConnectionsRoute._addFileChildren(
  ApiConnectionsRouteChildren,
)

interface ApiEngagementsRouteChildren {
  ApiEngagementsIdRoute: typeof ApiEngagementsIdRoute
}

const ApiEngagementsRouteChildren: ApiEngagementsRouteChildren = {
  ApiEngagementsIdRoute: ApiEngagementsIdRoute,
}

const ApiEngagementsRouteWithChildren = ApiEngagementsRoute._addFileChildren(
  ApiEngagementsRouteChildren,
)

interface ApiExportsIdRouteChildren {
  ApiExportsIdArchiveRoute: typeof ApiExportsIdArchiveRoute
}

const ApiExportsIdRouteChildren: ApiExportsIdRouteChildren = {
  ApiExportsIdArchiveRoute: ApiExportsIdArchiveRoute,
}

const ApiExportsIdRouteWithChildren = ApiExportsIdRoute._addFileChildren(
  ApiExportsIdRouteChildren,
)

interface ApiExportsRouteChildren {
  ApiExportsIdRoute: typeof ApiExportsIdRouteWithChildren
  ApiExportsPreviewRoute: typeof ApiExportsPreviewRoute
}

const ApiExportsRouteChildren: ApiExportsRouteChildren = {
  ApiExportsIdRoute: ApiExportsIdRouteWithChildren,
  ApiExportsPreviewRoute: ApiExportsPreviewRoute,
}

const ApiExportsRouteWithChildren = ApiExportsRoute._addFileChildren(
  ApiExportsRouteChildren,
)

interface ApiIntakesIdRouteChildren {
  ApiIntakesIdPreviewRoute: typeof ApiIntakesIdPreviewRoute
}

const ApiIntakesIdRouteChildren: ApiIntakesIdRouteChildren = {
  ApiIntakesIdPreviewRoute: ApiIntakesIdPreviewRoute,
}

const ApiIntakesIdRouteWithChildren = ApiIntakesIdRoute._addFileChildren(
  ApiIntakesIdRouteChildren,
)

interface ApiIntakesRouteChildren {
  ApiIntakesIdRoute: typeof ApiIntakesIdRouteWithChildren
}

const ApiIntakesRouteChildren: ApiIntakesRouteChildren = {
  ApiIntakesIdRoute: ApiIntakesIdRouteWithChildren,
}

const ApiIntakesRouteWithChildren = ApiIntakesRoute._addFileChildren(
  ApiIntakesRouteChildren,
)

interface ApiMissionsIdRouteChildren {
  ApiMissionsIdRosterRoute: typeof ApiMissionsIdRosterRoute
}

const ApiMissionsIdRouteChildren: ApiMissionsIdRouteChildren = {
  ApiMissionsIdRosterRoute: ApiMissionsIdRosterRoute,
}

const ApiMissionsIdRouteWithChildren = ApiMissionsIdRoute._addFileChildren(
  ApiMissionsIdRouteChildren,
)

interface ApiMissionsRouteChildren {
  ApiMissionsIdRoute: typeof ApiMissionsIdRouteWithChildren
}

const ApiMissionsRouteChildren: ApiMissionsRouteChildren = {
  ApiMissionsIdRoute: ApiMissionsIdRouteWithChildren,
}

const ApiMissionsRouteWithChildren = ApiMissionsRoute._addFileChildren(
  ApiMissionsRouteChildren,
)

interface ApiAuthGithubRouteChildren {
  ApiAuthGithubCallbackRoute: typeof ApiAuthGithubCallbackRoute
}

const ApiAuthGithubRouteChildren: ApiAuthGithubRouteChildren = {
  ApiAuthGithubCallbackRoute: ApiAuthGithubCallbackRoute,
}

const ApiAuthGithubRouteWithChildren = ApiAuthGithubRoute._addFileChildren(
  ApiAuthGithubRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiClientsRoute: ApiClientsRouteWithChildren,
  ApiConnectionsRoute: ApiConnectionsRouteWithChildren,
  ApiEngagementsRoute: ApiEngagementsRouteWithChildren,
  ApiExportsRoute: ApiExportsRouteWithChildren,
  ApiIntakesRoute: ApiIntakesRouteWithChildren,
  ApiMissionsRoute: ApiMissionsRouteWithChildren,
  ApiAuthGithubRoute: ApiAuthGithubRouteWithChildren,
  ApiPreflightBlastRadiusRoute: ApiPreflightBlastRadiusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
